name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: 'Create env file'
        run: |
          echo "${{ secrets.ENV }}" > .env
      - run: npm install
      - run: npm run eslint
      - run: npm test
      - name: 'Install in frontend'
        working-directory: ./bloglist-frontend
        run: npm install
      - name: 'Lint frontend'
        working-directory: ./bloglist-frontend
        run: npm run eslint
      - name: 'Test frontend'
        working-directory: ./bloglist-frontend
        run: npm test
      - name: 'Build frontend'
        working-directory: ./bloglist-frontend
        run: npm run build
      - name: e2e tests
        uses: cypress-io/github-action@v5
        with:
          working-directory: ./bloglist-frontend
          command: npm run test:e2e
          start: npm --prefix .. run start:test
          wait-on: http://localhost:3003
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
      
  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-20.04
    if: ${{ github.event_name == 'push' && !contains(join(github.event.commits.*.message), '#skip') }}
    steps:
      - uses: actions/checkout@v3
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.55.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
